"use client"
import { Suspense } from 'react'
import { Montserrat } from 'next/font/google'
import {AnimatePresence} from 'framer-motion';
import Header from '@/components/Header'

import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AnimatePresence mode="wait" onExitComplete={() => window.scrollTo(0, 0)}>
          <Header />
          <Suspense fallback={""}>
            {children}
          </Suspense>
        </AnimatePresence>
      </body>
    </html>
  )
}
